spring:
  application:
    name: spring_ai_service
  ai:
    ollama:
      base-url: http://ollama:11434
      chat:
        model: gemma3:4b-it-q4_K_M
  datasource:
    url: jdbc:postgresql://postgres:5432/ragdb
    username: postgres
    password: postgres
  main:
    allow-circular-references: true

